# Generated by Django 5.2.1 on 2025-07-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_investment_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
