name: Daily Investment Update

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC
  workflow_dispatch:      # Optional: manual run button

permissions:
  contents: write  # Needed to push to repo

jobs:
  update-balance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Balance Collector
        env:
          PYTHONPATH: ${{ github.workspace }}/backend
          DJANGO_SETTINGS_MODULE: backend.backend.settings
          QUOTE_CURRENCY: USD
          KRAKEN_API_KEY: ${{ secrets.KRAKEN_API_KEY }}
          KRAKEN_API_SECRET: ${{ secrets.KRAKEN_API_SECRET }}
        run: |
          python backend/automation/add_balances.py

      - name: Commit and push updated data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          git stash --include-untracked
          git pull --rebase
          git stash pop || true

          git add backend/automation/daily_balances.csv backend/automation/scheduler_log.txt
          git commit -m "Auto update: daily balances [${{ github.run_id }}]" || echo "No changes to commit"
          git push
