name: Daily Investment Scheduler

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC
  workflow_dispatch:      # Allow manual trigger from GitHub

permissions:
  contents: write  # Allows GitHub Actions to push commits

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Django script
        env:
          DJANGO_SETTINGS_MODULE: backend.settings
          QUOTE_CURRENCY: USD
          KRAKEN_API_KEY: ${{ secrets.KRAKEN_API_KEY }}
          KRAKEN_API_SECRET: ${{ secrets.KRAKEN_API_SECRET }}
        run: |
          python backend/investment_scheduler.py

      - name: Commit and push updated scheduler log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          # Set token-based origin (so git pull/push works in GitHub Actions)
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          git pull --rebase

          git add backend/scheduler_log.txt
          git commit -m "Update scheduler_log.txt [auto]" || echo "No changes to commit"
          git push
